"""Rules for downloading raw data and preparing genotypes.

- FASTQ files are downloaded from the SRA with the SRA Toolkit
  (prefetch + fasterq-dump), keyed on the run accessions listed in each
  tissue's fastq_map.txt (generated by scripts/setup/setup_sra.py).
- The unphased genotype VCF is downloaded from RatGTEx, its REF alleles are
  set to match the reference genome, and it is phased with Beagle.
"""

wildcard_constraints:
    # SRA/ENA/DDBJ run accessions, e.g. SRR1234567. The trailing digits keep
    # this from matching the paired FASTQ suffixes (_1 / _2), which lets
    # Snakemake pick the single- vs paired-end rule unambiguously.
    run = r"[SED]RR[0-9]+",
    # Genotype dataset names contain no dots or slashes, so this does not match
    # the ".phased" or "original/" paths below.
    geno_dataset = r"[A-Za-z0-9_]+",
    # Chromosome names, e.g. chr1..chr20. Non-empty so the per-chromosome phased
    # VCF pattern doesn't match the concatenated final one.
    chrom = r"chr[0-9]+",


rule sra_fastq_paired:
    """Download a paired-end SRA run and write gzipped R1/R2 FASTQs."""
    output:
        tmp = temp(directory("fastq/{tissue}/tmp_paired_{run}")),
    resources:
        mem_mb = 4000,
        # Custom resource limiting concurrent SRA downloads. The total pool
        # defaults to 3 (set via the Snakemake profile's `resources:` key or
        # `--resources sra_downloads=N`), so at most 3 of these jobs run at once.
        sra_downloads = 1,
    container:
        "images/sratools.sif"
    shell:
        """
        rm -rf {output.tmp}
        mkdir -p {output.tmp}
        prefetch {wildcards.run} --output-directory {output.tmp} --max-size u
        """

rule sra_fastq_dump_paired:
    """fasterq-dump on the prefetched data"""
    input:
        tmp = "fastq/{tissue}/tmp_paired_{run}"
    output:
        r1 = "fastq/{tissue}/{run}_1.fastq.gz",
        r2 = "fastq/{tissue}/{run}_2.fastq.gz",
    container:
        "images/sratools.sif"
    threads: 6
    resources:
        mem_mb = 8000,
        runtime = '8h',
    shell:
        """
        fasterq-dump {input.tmp}/{wildcards.run} \
            --split-3 \
            --threads {threads} \
            --outdir {input.tmp}
        gzip -c {input.tmp}/{wildcards.run}_1.fastq > {output.r1}
        gzip -c {input.tmp}/{wildcards.run}_2.fastq > {output.r2}
        """

rule sra_fastq_single:
    """Prefetch a single-end SRA run (download step; see sra_fastq_dump_single)."""
    output:
        tmp = temp(directory("fastq/{tissue}/tmp_single_{run}")),
    resources:
        mem_mb = 4000,
        # See sra_fastq_paired: limits concurrent SRA downloads (pool default 3).
        sra_downloads = 1,
    container:
        "images/sratools.sif"
    shell:
        """
        rm -rf {output.tmp}
        mkdir -p {output.tmp}
        prefetch {wildcards.run} --output-directory {output.tmp} --max-size u
        """

rule sra_fastq_dump_single:
    """fasterq-dump on the prefetched single-end data."""
    input:
        tmp = "fastq/{tissue}/tmp_single_{run}"
    output:
        "fastq/{tissue}/{run}.fastq.gz",
    threads: 6
    resources:
        mem_mb = 8000,
        runtime = '8h',
    container:
        "images/sratools.sif"
    shell:
        """
        fasterq-dump {input.tmp}/{wildcards.run} \
            --split-3 \
            --threads {threads} \
            --outdir {input.tmp}
        gzip -c {input.tmp}/{wildcards.run}.fastq > {output}
        """


rule download_genotypes:
    """Download the unphased genotype VCF for all rats from RatGTEx.
    The URL for each genotype dataset is given in config.yaml under `geno_url`.
    """
    output:
        "geno/original/{geno_dataset}.vcf.gz"
    params:
        url = lambda w: config["geno_url"][w.geno_dataset],
    resources:
        runtime = '4h',
    container:
        "images/bioinfo.sif"
    shell:
        """
        mkdir -p geno/original
        wget --no-verbose -O {output} "{params.url}"
        """


rule process_genotypes:
    """Prepare downloaded genotypes for the pipeline.

    Mirrors scripts/setup/genotypes_v4.sh: set variant IDs, make REF alleles
    match the reference genome (plink2 --ref-from-fa, then drop remaining
    mismatches with bcftools norm --check-ref x), and keep only biallelic SNPs.
    """
    input:
        vcf = "geno/original/{geno_dataset}.vcf.gz",
        fasta = f"{GENOME_PREFIX}.fa",
    output:
        vcf = "geno/{geno_dataset}.vcf.gz",
        tbi = "geno/{geno_dataset}.vcf.gz.tbi",
    params:
        prefix = "geno/intermediate/{geno_dataset}",
    resources:
        mem_mb = 16000,
        runtime = '4h',
    container:
        "images/bioinfo.sif"
    shell:
        """
        mkdir -p geno/intermediate
        plink2 --vcf {input.vcf} \
            --chr 1-20 \
            --set-all-var-ids '@:#' \
            --fa {input.fasta} \
            --ref-from-fa force \
            --recode vcf \
            --output-chr chrM \
            --out {params.prefix}
        bgzip -f {params.prefix}.vcf
        bcftools norm {params.prefix}.vcf.gz \
            --rm-dup snps \
            --check-ref x \
            --fasta-ref {input.fasta} \
            -Ou | bcftools view \
            --min-alleles 2 \
            --max-alleles 2 \
            -O z -o {output.vcf}
        tabix -f -p vcf {output.vcf}
        """


rule phase_genotypes_chrom:
    """Phase a single chromosome with Beagle (reference-free / population phasing).
    Parallelized across chromosomes; the per-chromosome outputs are temporary
    and concatenated by phase_genotypes. An optional genetic map per dataset can
    be given in config.yaml under `geno_map`; without one Beagle assumes 1 cM/Mb.
    """
    input:
        vcf = "geno/{geno_dataset}.vcf.gz",
        tbi = "geno/{geno_dataset}.vcf.gz.tbi",
    output:
        vcf = temp("geno/intermediate/{geno_dataset}.phased.{chrom}.vcf.gz"),
    params:
        out_prefix = "geno/intermediate/{geno_dataset}.phased.{chrom}",
        map_arg = lambda w: (
            f"map={config['geno_map'][w.geno_dataset]}"
            if config.get("geno_map", {}).get(w.geno_dataset)
            else ""
        ),
    threads: 4
    resources:
        mem_mb = 16000,
        runtime = '12h',
    container:
        "images/bioinfo.sif"
    shell:
        """
        mkdir -p geno/intermediate
        beagle -Xmx{resources.mem_mb}m \
            gt={input.vcf} \
            chrom={wildcards.chrom} \
            out={params.out_prefix} \
            nthreads={threads} \
            {params.map_arg}
        """


rule phase_genotypes:
    """Concatenate the per-chromosome phased VCFs into the final phased VCF."""
    input:
        chroms = lambda w: expand(
            "geno/intermediate/{geno_dataset}.phased.{chrom}.vcf.gz",
            geno_dataset=w.geno_dataset,
            chrom=CHROMS,
        ),
    output:
        vcf = "geno/{geno_dataset}.phased.vcf.gz",
        tbi = "geno/{geno_dataset}.phased.vcf.gz.tbi",
    resources:
        mem_mb = 8000,
        runtime = '4h',
    container:
        "images/bioinfo.sif"
    shell:
        """
        bcftools concat -Oz -o {output.vcf} {input.chroms}
        tabix -f -p vcf {output.vcf}
        """
