"""Rules for downloading raw data and preparing genotypes.

- FASTQ files are downloaded from the SRA with the SRA Toolkit
  (prefetch + fasterq-dump), keyed on the run accessions listed in each
  tissue's fastq_map.txt (generated by scripts/setup/setup_sra.py).
- The unphased genotype VCF is downloaded from RatGTEx, its REF alleles are
  set to match the reference genome, and it is phased with Beagle.
"""

wildcard_constraints:
    # SRA/ENA/DDBJ run accessions, e.g. SRR1234567. The trailing digits keep
    # this from matching the paired FASTQ suffixes (_1 / _2), which lets
    # Snakemake pick the single- vs paired-end rule unambiguously.
    run = r"[SED]RR[0-9]+",
    # Genotype dataset names contain no dots or slashes, so this does not match
    # the ".phased" or "original/" paths below.
    geno_dataset = r"[A-Za-z0-9_]+",


rule sra_fastq_paired:
    """Download a paired-end SRA run and write gzipped R1/R2 FASTQs."""
    output:
        r1 = "fastq/{tissue}/{run}_1.fastq.gz",
        r2 = "fastq/{tissue}/{run}_2.fastq.gz",
    params:
        tmp = "fastq/{tissue}/tmp_{run}",
    threads: 6
    resources:
        mem_mb = 8000,
        runtime = '8h',
    shell:
        """
        rm -rf {params.tmp}
        mkdir -p {params.tmp}
        prefetch {wildcards.run} --output-directory {params.tmp} --max-size u
        fasterq-dump {params.tmp}/{wildcards.run} \
            --split-3 \
            --threads {threads} \
            --outdir {params.tmp}
        gzip -c {params.tmp}/{wildcards.run}_1.fastq > {output.r1}
        gzip -c {params.tmp}/{wildcards.run}_2.fastq > {output.r2}
        rm -rf {params.tmp}
        """


rule sra_fastq_single:
    """Download a single-end SRA run and write a gzipped FASTQ."""
    output:
        "fastq/{tissue}/{run}.fastq.gz",
    params:
        tmp = "fastq/{tissue}/tmp_{run}",
    threads: 6
    resources:
        mem_mb = 8000,
        runtime = '8h',
    shell:
        """
        rm -rf {params.tmp}
        mkdir -p {params.tmp}
        prefetch {wildcards.run} --output-directory {params.tmp} --max-size u
        fasterq-dump {params.tmp}/{wildcards.run} \
            --split-3 \
            --threads {threads} \
            --outdir {params.tmp}
        gzip -c {params.tmp}/{wildcards.run}.fastq > {output}
        rm -rf {params.tmp}
        """


rule download_genotypes:
    """Download the unphased genotype VCF for all rats from RatGTEx.
    The URL for each genotype dataset is given in config.yaml under `geno_url`.
    """
    output:
        "geno/original/{geno_dataset}.vcf.gz"
    params:
        url = lambda w: config["geno_url"][w.geno_dataset],
    resources:
        runtime = '4h',
    shell:
        """
        mkdir -p geno/original
        wget --no-verbose -O {output} "{params.url}"
        """


rule process_genotypes:
    """Prepare downloaded genotypes for the pipeline.

    Mirrors scripts/setup/genotypes_v4.sh: set variant IDs, make REF alleles
    match the reference genome (plink2 --ref-from-fa, then drop remaining
    mismatches with bcftools norm --check-ref x), and keep only biallelic SNPs.
    """
    input:
        vcf = "geno/original/{geno_dataset}.vcf.gz",
        fasta = f"{GENOME_PREFIX}.fa",
    output:
        vcf = "geno/{geno_dataset}.vcf.gz",
        tbi = "geno/{geno_dataset}.vcf.gz.tbi",
    params:
        prefix = "geno/intermediate/{geno_dataset}",
    resources:
        mem_mb = 16000,
        runtime = '4h',
    shell:
        """
        mkdir -p geno/intermediate
        plink2 --vcf {input.vcf} \
            --chr 1-20 \
            --set-all-var-ids '@:#' \
            --fa {input.fasta} \
            --ref-from-fa force \
            --recode vcf \
            --output-chr chrM \
            --out {params.prefix}
        bgzip -f {params.prefix}.vcf
        bcftools norm {params.prefix}.vcf.gz \
            --rm-dup snps \
            --check-ref x \
            --fasta-ref {input.fasta} \
            -Ou | bcftools view \
            --min-alleles 2 \
            --max-alleles 2 \
            -O z -o {output.vcf}
        tabix -f -p vcf {output.vcf}
        """


rule phase_genotypes:
    """Phase genotypes with Beagle (reference-free / population phasing).
    An optional genetic map per dataset can be given in config.yaml under
    `geno_map`; without one Beagle assumes 1 cM/Mb.
    """
    input:
        vcf = "geno/{geno_dataset}.vcf.gz",
        tbi = "geno/{geno_dataset}.vcf.gz.tbi",
    output:
        vcf = "geno/{geno_dataset}.phased.vcf.gz",
        tbi = "geno/{geno_dataset}.phased.vcf.gz.tbi",
    params:
        out_prefix = "geno/{geno_dataset}.phased",
        map_arg = lambda w: (
            f"map={config['geno_map'][w.geno_dataset]}"
            if config.get("geno_map", {}).get(w.geno_dataset)
            else ""
        ),
    threads: 8
    resources:
        mem_mb = 32000,
        runtime = '24h',
    shell:
        """
        beagle -Xmx{resources.mem_mb}m \
            gt={input.vcf} \
            out={params.out_prefix} \
            nthreads={threads} \
            {params.map_arg}
        tabix -f -p vcf {output.vcf}
        """
